### ISSUE TITLE
Java.math.BigDecimal cannot be cast to java.lang.Integer Error "Embedding query from store" | Azure AI search 

### ISSUE THREAD

**Issue by ajaytiwa** [MuleSoft-AI-Chain-Project/mule-vectors-connector#57]
Hello ,

I am getting below error while performing query operation from Azure AI search.

I tried all the options between .2 to .8 (minScore) but getting same error.

ERROR 2024-11-26 22:50:58,520 [[MuleRuntime].uber.10: [webcrawling].vectorsFlow.CPU_LITE @1dbf9f60] [processor: vectorsFlow/processors/0; event: cd4b3540-ac1a-11ef-a2f0-ac74b1e63e98] org.mule.runtime.core.internal.exception.OnErrorPropagateHandler: 
********************************************************************************
Message               : java.math.BigDecimal cannot be cast to java.lang.Integer
Element               : vectorsFlow/processors/0 @ webcrawling:vectors.xml:16 (Embedding query from store)
Element DSL           : <ms-vectors:embedding-query-from-store doc:name="Embedding query from store" doc:id="543c53cb-fa5d-4faa-860b-1bf79eade2f0" config-ref="MuleSoft_Vectors_Connector_Config" storeName="testindex" question="#["Can you provide summary of Tech evaluation?"]" maxResults="3" minScore="0.8" embeddingModelName="text-embedding-3-small"></ms-vectors:embedding-query-from-store>
Error type            : MS-VECTORS:EMBEDDING_OPERATIONS_FAILURE
FlowStack             : at vectorsFlow(vectorsFlow/processors/0 @ webcrawling:vectors.xml:16 (Embedding query from store))
Payload Type          : org.mule.runtime.core.internal.streaming.bytes.ManagedCursorStreamProvider
--------------------------------------------------------------------------------
Root Exception stack trace:
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Integer
	at org.mule.extension.mulechain.vectors.internal.operation.EmbeddingOperations.queryFromEmbedding(EmbeddingOperations.java:354)
	at org.mule.extension.mulechain.vectors.internal.operation.EmbeddingOperations$queryFromEmbedding$MethodComponentExecutor_webcrawling.execute(Unknown Source)
	at org.mule.runtime.module.extension.internal.runtime.execution.GeneratedMethodComponentExecutor.execute(GeneratedMethodComponentExecutor.java:98)
	at org.mule.runtime.module.extension.internal.runtime.execution.CompletableMethodOperationExecutor.doExecute(CompletableMethodOperationExecutor.java:29)
	at org.mule.runtime.module.extension.internal.runtime.execution.AbstractCompletableMethodOperationExecutor.execute(AbstractCompletableMethodOperationExecutor.java:63)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.executeCommand(DefaultExecutionMediator.java:232)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.executeWithInterceptors(DefaultExecutionMediator.java:216)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.lambda$execute$1(DefaultExecutionMediator.java:125)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.lambda$new$0(DefaultExecutionMediator.java:65)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.withExecutionTemplate(DefaultExecutionMediator.java:301)
	at org.mule.runtime.module.extension.internal.runtime.operation.DefaultExecutionMediator.execute(DefaultExecutionMediator.java:124)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.executeOperation(ComponentMessageProcessor.java:575)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.prepareAndExecuteOperation(ComponentMessageProcessor.java:800)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.access$100(ComponentMessageProcessor.java:197)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor$4.lambda$innerEventDispatcher$6(ComponentMessageProcessor.java:660)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:482)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:496)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.lambda$onEvent$13(ComponentMessageProcessor.java:443)
	at org.mule.runtime.core.internal.policy.DefaultPolicyManager.lambda$static$0(DefaultPolicyManager.java:85)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.onEvent(ComponentMessageProcessor.java:454)
	at org.mule.runtime.module.extension.internal.runtime.operation.ComponentMessageProcessor.lambda$null$6(ComponentMessageProcessor.java:395)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:482)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:496)
	at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:485)
	at org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:480)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:351)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:447)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:534)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:152)
	at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by tbolis-at-mulesoft** [comment]
@ajaytiwa which version of the connector are you using?

**Comment by tbolis-at-mulesoft** [comment]
The error is caused by maxResults and not by minscore.

**Comment by ajaytiwa** [comment]
<img width="638" alt="image" src="https://github.com/user-attachments/assets/c91f2e98-ab63-4b2a-945d-25a4e999d556">
That's how my current config looks like
@tbolis-at-mulesoft

**Comment by tbolis-at-mulesoft** [comment]
Can you share the java version you used to compile the connector?

**Comment by ajaytiwa** [comment]
@tbolis-at-mulesoft  FYI.. I tested the same with 0.2.50 as well but getting same error..

**Comment by tbolis-at-mulesoft** [comment]
Ok thank you I’ll give prority to this

**Comment by ajaytiwa** [comment]
Final error message was same which I originally posted , will share full stacktrace tomorrow

**Comment by tbolis-at-mulesoft** [comment]
Ok thank you! Also share the xml for the connector operation.

**Comment by tbolis-at-mulesoft** [comment]
I wa able to only partially reproduce the error by sending a double as max result "3.0" instead of "3". Then I made the code more robust. Now I ask you to try to compile the develop branch and see if the error is gone or not. Thank you.

**Comment by ajaytiwa** [comment]
@tbolis-at-mulesoft  I tested from develop branch and issue got fixed .. thanks a ton for your quick resolution :)
